require:
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Rails/Present:
  Exclude:
    - bin/*

RSpec/NestedGroups:
  Exclude:
    - spec/requests/**/*.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb

I18n/RailsI18n:
  Exclude:
    - bin/*
    - db/**/*.rb
    - spec/**/*

I18n/GetText:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - db/**/*.rb

Rails/SkipsModelValidations:
  Exclude:
    - db/**/*.rb
