shared:
  adjectives:
    - Adorable
    - Adventurous
    - Agreeable
    - Brainy
    - Brave
    - Bright
    - Calm
    - Charming
    - Cheerful
    - Clever
    - Colorful
    - Comfortable
    - Courageous
    - Curious
    - Delightful
    - Determined
    - Encouraging
    - Energetic
    - Enthusiastic
    - Excited
    - Famous
    - Fancy
    - Fantastic
    - Friendly
    - Funny
    - Gentle
    - Glamorous
    - Gleaming
    - Glorious
    - Good
    - Graceful
    - Happy
    - Helpful
    - Hilarious
    - Inquisitive
    - Jolly
    - Joyous
    - Kind
    - Light
    - Lively
    - Lucky
    - Magnificent
    - Modern
    - Nice
    - Outstanding
    - Pleasant
    - Powerful
    - Precious
    - Proud
    - Quaint
    - Shiny
    - Smiling
    - Sparkling
    - Splendid
    - Successful
    - Super
    - Talented
    - Thankful
    - Thoughtful
    - Vast
    - Victorious
    - Vivacious
    - Witty
    - Zany
    - Zealous
  animals:
    - Alligator
    - Alpaca
    - Ant
    - Antelope
    - Armadillo
    - Badger
    - Bat
    - Bear
    - Bee
    - Beetle
    - Buffalo
    - Butterfly
    - Camel
    - Caribou
    - Cheetah
    - Chimpanzee
    - Chinchilla
    - Cicada
    - Clam
    - Cod
    - Coyote
    - Cricket
    - Crocodile
    - Crow
    - Deer
    - Dolphin
    - Donkey
    - Duck
    - Eagle
    - Eel
    - Elephant
    - Elk
    - Ferret
    - Fish
    - Gerbil
    - Giraffe
    - Gnat
    - Gnu
    - Goat
    - Goldfish
    - Goose
    - Grasshopper
    - Hamster
    - Hare
    - Hedgehog
    - Herring
    - Hornet
    - Horse
    - Hound
    - Hyena
    - Impala
    - Jackal
    - Jellyfish
    - Kangaroo
    - Koala
    - Leopard
    - Lion
    - Lizard
    - Llama
    - Locust
    - Macaw
    - Mallard
    - Mammoth
    - Manatee
    - Marten
    - Mink
    - Minnow
    - Mole
    - Moose
    - Mouse
    - Mule
    - Muskrat
    - Otter
    - Ox
    - Oyster
    - Platypus
    - Porcupine
    - Porpoise
    - Pug
    - Rabbit
    - Raven
    - Reindeer
    - Rhinoceros
    - Salmon
    - Sardine
    - Scorpion
    - Sea lion
    - Seal
    - Serval
    - Shark
    - Sheep
    - Snail
    - Spider
    - Squirrel
    - Swan
    - Termite
    - Tiger
    - Tortoise
    - Trout
    - Turtle
    - Wallaby
    - Wasp
    - Wildebeest
    - Wolf
    - Wombat
    - Woodchuck
    - Yak
    - Yellowjacket
    - Zebra

test:
  adjectives:
    - Testing
  animals:
    - Guest
