name: Lint

on: [pull_request]

jobs:
  standard:
    runs-on: ubuntu-latest

    env:
      # Requires the relevant gems to have a separate group in `Gemfile`
      # At the time of writing there is no way to only install gems in specific group(s) by specifying the group name(s)
      BUNDLE_WITHOUT: "production"
      # `MAKE="make --jobs $(nproc)"` is from
      # https://build.betterup.com/one-weird-trick-that-will-speed-up-your-bundle-install/
      # Only works for MRI
      #
      # Using 4 since https://github.com/ruby/setup-ruby use 4
      MAKE: "make --jobs 4"
      BUNDLE_PATH: "vendor/bundle"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # If your project only specifies its Ruby version in its
      # Gemfile, you'll need to specify a version for the
      # action to use. See documentation for the
      # ruby/setup-ruby action for details.
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Lint
        run: bin/standardrb
