# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruby

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PG_PASSWORD: postgres

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      - name: Install dependencies
        run: |
          bundle install
          bundle exec rails webpacker:install
      - name: Create DB
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:prepare
      - name: Assets Cache
        id: assets-cache
        uses: actions/cache@v2
        with:
          path: |
            public/assets
            public/packs-test
          key: ${{ runner.os }}-assets
      - name: Precompile Assets
        run: bundle exec rails assets:precompile
      - name: Ruby tests
        run: bundle exec rspec
