# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruby

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PG_PASSWORD: postgres

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Create DB
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:prepare
      - uses: actions/cache@v3
        with:
          path: |
            public/assets
            app/assets/builds
            tmp/cache/assets
          key: ${{ runner.os }}-assets
      - name: Build assets
        run: bin/rails assets:precompile
      - name: Ruby tests
        run: bin/rspec
